version: '3.9'
services:
  nginx:
    container_name: url_nginx
    build:
      context: ./docker/nginx
      args:
        HOST_UID: ${HOST_UID}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    networks:
      url:
        aliases:
          - url.local
  php:
    container_name: url_php
    build:
      context: ./docker/php
      args:
        HOST_UID: ${HOST_UID}
    volumes:
      - ./:/var/www/html
    environment:
      HOST_UID: ${HOST_UID}
      XDEBUG_CONFIG: remote_host=${XDEBUG_IP} remote_port=${XDEBUG_PORT}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    networks:
      - url
  db:
    container_name: url_db
    build:
        context: ./docker/mysql
        args:
            HOST_UID: ${HOST_UID}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./docker/runtime/mysql:/var/lib/mysql
        - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
        - "${MYSQL_PORT}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: url
        MYSQL_USER: docker
        MYSQL_PASSWORD: secret
    networks:
        - url
networks:
  url:
    external: true
